default: &default
  adapter: mysql2
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %> 
  encoding: utf8
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  port: 3306
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false

development:
  <<: *default
  database: InstabugApiTestDev

test:
  <<: *default
  database: InstabugApiTest

production:
  <<: *default
  database: InstabugApiProduction
